// import { ReferAndEarnEntity } from '.';

export const referAndEarnData = [
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Successful',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Unsuccessful',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Pending',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Unsuccessful',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Pending',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Unsuccessful',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Successful',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Pending',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
  {
    amount: '1971',
    date_created: 'Fri Feb 18 2022',
    id: 93418,
    play_percentage: '45',
    referred_users: 'Shelley Ankunding',
    status: 'Pending',
    subRows: undefined,
    user_email: 'Delphia.Schamberger@hotmail.com',
  },
];
